# Generated by Django 5.2 on 2025-05-06 01:36

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_id",
                    models.CharField(
                        default=game.models.generate_game_id, max_length=8, unique=True
                    ),
                ),
                (
                    "fen",
                    models.TextField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
                    ),
                ),
                ("status", models.CharField(default="waiting", max_length=20)),
                (
                    "player_white",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "player_black",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("white_ready", models.BooleanField(default=False)),
                ("black_ready", models.BooleanField(default=False)),
                ("turn", models.CharField(default="w", max_length=1)),
                ("spectator_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
