# Generated by Django 5.2 on 2025-05-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="in_check",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="last_move",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="move_history",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for players"),
                    ("active", "Game in progress"),
                    ("checkmate", "Checkmate"),
                    ("stalemate", "Stalemate"),
                    ("draw", "Draw"),
                    ("abandoned", "Game abandoned"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
