# Generated by Django 5.2 on 2025-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_in_check_game_last_move_game_move_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="color_reservations",
            field=models.JSONField(default=dict),
        ),
    ]
